auto_scale_lr = dict(base_batch_size=16, enable=True)
backend_args = None
class_names = [
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
]
corruption_root = '/workspace/mmdetection3d/data/multicorrupt'
corruptions = [
    'beamsreducing',
    'dark',
    'lidar_fog',
    'camera_fog',
    'lidar_motionblur',
    'camera_motionblur',
    'none',
]
custom_hooks = [
    dict(train_module_names=[
        'pts_bbox_head',
    ], type='FreezeLayersHook'),
]
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'projects.BEVFusion.bevfusion',
        'projects.UniM2AE',
        'projects.CMT',
    ])
data_prefix = dict(
    CAM_BACK='samples/CAM_BACK',
    CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
    CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
    CAM_FRONT='samples/CAM_FRONT',
    CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
    CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
    pts='samples/LIDAR_TOP',
    sweeps='sweeps/LIDAR_TOP')
data_root = '/workspace/mmdetection3d/data/nuscenes/'
dataset_type = 'NuScenesDiverseCorruptDataset'
db_sampler = dict(
    classes=[
        'car',
        'truck',
        'construction_vehicle',
        'bus',
        'trailer',
        'barrier',
        'motorcycle',
        'bicycle',
        'pedestrian',
        'traffic_cone',
    ],
    data_root='/workspace/mmdetection3d/data/nuscenes/',
    info_path=
    '/workspace/mmdetection3d/data/nuscenes/nuscenes_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(
            barrier=5,
            bicycle=5,
            bus=5,
            car=5,
            construction_vehicle=5,
            motorcycle=5,
            pedestrian=5,
            traffic_cone=5,
            trailer=5,
            truck=5)),
    rate=1.0,
    sample_groups=dict(
        barrier=2,
        bicycle=6,
        bus=4,
        car=2,
        construction_vehicle=7,
        motorcycle=6,
        pedestrian=2,
        traffic_cone=2,
        trailer=6,
        truck=3))
default_hooks = dict(
    checkpoint=dict(interval=4, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
drop_info = (
    dict({
        0: dict(drop_range=(
            0,
            30,
        ), max_tokens=30),
        1: dict(drop_range=(
            30,
            60,
        ), max_tokens=60),
        2: dict(drop_range=(
            60,
            100,
        ), max_tokens=100),
        3: dict(drop_range=(
            100,
            200,
        ), max_tokens=200),
        4: dict(drop_range=(
            200,
            100000,
        ), max_tokens=256)
    }),
    dict({
        0: dict(drop_range=(
            0,
            30,
        ), max_tokens=30),
        1: dict(drop_range=(
            30,
            60,
        ), max_tokens=60),
        2: dict(drop_range=(
            60,
            100,
        ), max_tokens=100),
        3: dict(drop_range=(
            100,
            200,
        ), max_tokens=200),
        4: dict(drop_range=(
            200,
            100000,
        ), max_tokens=256)
    }),
)
drop_info_test = dict({
    0: dict(drop_range=(
        0,
        30,
    ), max_tokens=30),
    1: dict(drop_range=(
        30,
        60,
    ), max_tokens=60),
    2: dict(drop_range=(
        60,
        100,
    ), max_tokens=100),
    3: dict(drop_range=(
        100,
        200,
    ), max_tokens=200),
    4: dict(drop_range=(
        200,
        100000,
    ), max_tokens=256)
})
drop_info_training = dict({
    0: dict(drop_range=(
        0,
        30,
    ), max_tokens=30),
    1: dict(drop_range=(
        30,
        60,
    ), max_tokens=60),
    2: dict(drop_range=(
        60,
        100,
    ), max_tokens=100),
    3: dict(drop_range=(
        100,
        200,
    ), max_tokens=200),
    4: dict(drop_range=(
        200,
        100000,
    ), max_tokens=256)
})
encoder_blocks = 8
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
grid_size = (
    720,
    720,
    1,
)
input_modality = dict(use_camera=True, use_lidar=True)
launcher = 'none'
load_from = '/workspace/mmdetection3d/work_dirs/cmt_sst/epoch_20.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
metainfo = dict(classes=[
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
])
model = dict(
    data_preprocessor=dict(
        type='Det3DDataPreprocessor',
        voxel=True,
        voxel_layer=dict(
            max_num_points=-1,
            max_voxels=(
                -1,
                -1,
            ),
            point_cloud_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            voxel_size=(
                0.15,
                0.15,
                8,
            )),
        voxel_type='dynamic'),
    pts_backbone=dict(
        conv_in_channel=128,
        conv_kwargs=[
            dict(kernel_size=3, padding=1, stride=2),
            dict(kernel_size=3, padding=1, stride=2),
        ],
        conv_out_channel=128,
        d_model=[
            128,
            128,
            128,
            128,
            128,
            128,
            128,
            128,
        ],
        debug=True,
        dim_feedforward=[
            256,
            256,
            256,
            256,
            256,
            256,
            256,
            256,
        ],
        masked=False,
        nhead=[
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
        ],
        num_attached_conv=2,
        num_blocks=8,
        output_shape=[
            720,
            720,
        ],
        type='SSTv2'),
    pts_bbox_head=dict(
        bbox_coder=dict(
            max_num=300,
            num_classes=10,
            pc_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            post_center_range=[
                -61.2,
                -61.2,
                -10.0,
                61.2,
                61.2,
                10.0,
            ],
            type='MultiTaskBBoxCoder',
            voxel_size=(
                0.15,
                0.15,
                8,
            )),
        common_heads=dict(
            center=(
                2,
                2,
            ),
            dim=(
                3,
                2,
            ),
            height=(
                1,
                2,
            ),
            rot=(
                2,
                2,
            ),
            vel=(
                2,
                2,
            )),
        downsample_scale=4,
        hidden_dim=256,
        in_channels=128,
        loss_bbox=dict(
            loss_weight=0.25, reduction='mean', type='mmdet.L1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2,
            loss_weight=2.0,
            reduction='mean',
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_heatmap=dict(
            loss_weight=1.0, reduction='mean', type='mmdet.GaussianFocalLoss'),
        separate_head=dict(
            final_kernel=1, init_bias=-2.19, type='SeparateTaskHead'),
        tasks=[
            dict(
                class_names=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                num_class=10),
        ],
        transformer=dict(
            decoder=dict(
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='MultiheadAttention'),
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='PETRMultiheadFlashAttention'),
                    ],
                    feedforward_channels=1024,
                    ffn_cfgs=dict(
                        act_cfg=dict(inplace=True, type='ReLU'),
                        embed_dims=256,
                        feedforward_channels=1024,
                        ffn_drop=0.0,
                        num_fcs=2,
                        type='FFN'),
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='PETRTransformerDecoderLayer',
                    with_cp=False),
                type='PETRTransformerDecoder'),
            type='CmtLidarTransformer'),
        type='CmtLidarHead'),
    pts_middle_encoder=dict(
        debug=True,
        drop_info=(
            dict({
                0: dict(drop_range=(
                    0,
                    30,
                ), max_tokens=30),
                1: dict(drop_range=(
                    30,
                    60,
                ), max_tokens=60),
                2: dict(drop_range=(
                    60,
                    100,
                ), max_tokens=100),
                3: dict(drop_range=(
                    100,
                    200,
                ), max_tokens=200),
                4: dict(drop_range=(
                    200,
                    100000,
                ), max_tokens=256)
            }),
            dict({
                0: dict(drop_range=(
                    0,
                    30,
                ), max_tokens=30),
                1: dict(drop_range=(
                    30,
                    60,
                ), max_tokens=60),
                2: dict(drop_range=(
                    60,
                    100,
                ), max_tokens=100),
                3: dict(drop_range=(
                    100,
                    200,
                ), max_tokens=200),
                4: dict(drop_range=(
                    200,
                    100000,
                ), max_tokens=256)
            }),
        ),
        mute=True,
        normalize_pos=False,
        pos_temperature=10000,
        shuffle_voxels=True,
        sparse_shape=(
            200,
            200,
            1,
        ),
        type='SSTInputLayerV2',
        window_shape=(
            16,
            16,
            1,
        )),
    pts_voxel_encoder=dict(
        feat_channels=[
            64,
            128,
        ],
        in_channels=5,
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN1d'),
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='DynamicVFE_Efficient',
        voxel_size=(
            0.15,
            0.15,
            8,
        ),
        with_cluster_center=True,
        with_distance=False,
        with_voxel_center=True),
    test_cfg=dict(
        pts=dict(
            dataset='nuScenes',
            grid_size=(
                720,
                720,
                1,
            ),
            max_num=200,
            nms_thr=0.2,
            nms_type=None,
            out_size_factor=4,
            pc_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            use_rotate_nms=True,
            voxel_size=(
                0.15,
                0.15,
                8,
            ))),
    train_cfg=dict(
        pts=dict(
            assigner=dict(
                cls_cost=dict(type='mmdet.FocalLossCost', weight=2.0),
                code_weights=[
                    2.0,
                    2.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    0.2,
                    0.2,
                ],
                iou_cost=dict(type='IoU3DCost_CMT', weight=0.0),
                pc_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                reg_cost=dict(type='BBox3DL1Cost', weight=0.25),
                type='HungarianAssigner3D_CMT'),
            code_weights=[
                2.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.2,
                0.2,
            ],
            dataset='nuScenes',
            gaussian_overlap=0.1,
            grid_size=(
                720,
                720,
                1,
            ),
            min_radius=2,
            out_size_factor=4,
            point_cloud_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            pos_weight=-1,
            voxel_size=(
                0.15,
                0.15,
                8,
            ))),
    type='CmtOldDetector')
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=1e-06, type='AdamW', weight_decay=0.01),
    type='AmpOptimWrapper')
out_size_factor = 4
param_scheduler = [
    dict(
        by_epoch=True,
        convert_to_iter_based=True,
        div_factor=8.0,
        eta_max=1e-06,
        final_div_factor=10000.0,
        pct_start=0.1,
        total_steps=8,
        type='OneCycleLR'),
]
point_cloud_range = [
    -54.0,
    -54.0,
    -5.0,
    53.95,
    53.95,
    2.95,
]
randomness = dict(diff_rank_seed=True, seed=100)
resume = False
sparse_shape = (
    200,
    200,
    1,
)
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                color_type='color',
                to_float32=True,
                type='BEVLoadMultiViewImageFromFiles'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                load_dim=5,
                pad_empty_sweeps=True,
                remove_close=True,
                sweeps_num=9,
                type='LoadPointsFromMultiSweeps',
                use_dim=5),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.48,
                    0.48,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    54.0,
                    54.0,
                    3.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'img',
                    'points',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='NuScenesDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='/workspace/mmdetection3d/data/nuscenes/nuscenes_infos_val.pkl',
    backend_args=None,
    data_root='/workspace/mmdetection3d/data/nuscenes/',
    metric='bbox',
    type='NuScenesMetric')
test_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        load_dim=5,
        pad_empty_sweeps=True,
        remove_close=True,
        sweeps_num=9,
        type='LoadPointsFromMultiSweeps',
        use_dim=5),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.48,
            0.48,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'img',
            'points',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'num_pts_feats',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        type='Pack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=8, val_interval=4)
train_dataloader = dict(
    batch_size=8,
    dataset=dict(
        ann_file='nuscenes_infos_train.pkl',
        box_type_3d='LiDAR',
        corruption_root='/workspace/mmdetection3d/data/multicorrupt',
        corruptions=[
            'beamsreducing',
            'dark',
            'lidar_fog',
            'camera_fog',
            'lidar_motionblur',
            'camera_motionblur',
            'none',
        ],
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                color_type='color',
                to_float32=True,
                type='BEVLoadMultiViewImageFromFiles'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                load_dim=5,
                pad_empty_sweeps=True,
                remove_close=True,
                sweeps_num=9,
                type='LoadPointsFromMultiSweeps',
                use_dim=5),
            dict(
                type='LoadAnnotations3D',
                with_attr_label=False,
                with_bbox_3d=True,
                with_label_3d=True),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=True,
                rand_flip=True,
                resize_lim=[
                    0.38,
                    0.55,
                ],
                rot_lim=[
                    -5.4,
                    5.4,
                ],
                type='ImageAug3D'),
            dict(
                db_sampler=dict(
                    classes=[
                        'car',
                        'truck',
                        'construction_vehicle',
                        'bus',
                        'trailer',
                        'barrier',
                        'motorcycle',
                        'bicycle',
                        'pedestrian',
                        'traffic_cone',
                    ],
                    data_root='/workspace/mmdetection3d/data/nuscenes/',
                    info_path=
                    '/workspace/mmdetection3d/data/nuscenes/nuscenes_dbinfos_train.pkl',
                    points_loader=dict(
                        backend_args=None,
                        coord_type='LIDAR',
                        load_dim=5,
                        type='LoadPointsFromFile',
                        use_dim=[
                            0,
                            1,
                            2,
                            3,
                            4,
                        ]),
                    prepare=dict(
                        filter_by_difficulty=[
                            -1,
                        ],
                        filter_by_min_points=dict(
                            barrier=5,
                            bicycle=5,
                            bus=5,
                            car=5,
                            construction_vehicle=5,
                            motorcycle=5,
                            pedestrian=5,
                            traffic_cone=5,
                            trailer=5,
                            truck=5)),
                    rate=1.0,
                    sample_groups=dict(
                        barrier=2,
                        bicycle=6,
                        bus=4,
                        car=2,
                        construction_vehicle=7,
                        motorcycle=6,
                        pedestrian=2,
                        traffic_cone=2,
                        trailer=6,
                        truck=3)),
                type='ObjectSample'),
            dict(
                rot_range=[
                    -0.78539816,
                    0.78539816,
                ],
                scale_ratio_range=[
                    0.9,
                    1.1,
                ],
                translation_std=0.5,
                type='BEVFusionGlobalRotScaleTrans'),
            dict(type='BEVFusionRandomFlip3D'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='PointsRangeFilter'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                fixed_prob=True,
                max_epoch=6,
                mode=1,
                offset=False,
                prob=0.0,
                ratio=0.5,
                rotate=1,
                type='GridMask',
                use_h=True,
                use_w=True),
            dict(type='PointShuffle'),
            dict(
                keys=[
                    'points',
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes',
                    'gt_labels',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'transformation_3d_flow',
                    'pcd_rotation',
                    'pcd_scale_factor',
                    'pcd_trans',
                    'img_aug_matrix',
                    'lidar_aug_matrix',
                    'num_pts_feats',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                type='Pack3DDetInputs'),
        ],
        return_corruption_info=True,
        test_mode=False,
        type='NuScenesDiverseCorruptDataset',
        use_valid_flag=True),
    num_workers=12,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        load_dim=5,
        pad_empty_sweeps=True,
        remove_close=True,
        sweeps_num=9,
        type='LoadPointsFromMultiSweeps',
        use_dim=5),
    dict(
        type='LoadAnnotations3D',
        with_attr_label=False,
        with_bbox_3d=True,
        with_label_3d=True),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=True,
        rand_flip=True,
        resize_lim=[
            0.38,
            0.55,
        ],
        rot_lim=[
            -5.4,
            5.4,
        ],
        type='ImageAug3D'),
    dict(
        db_sampler=dict(
            classes=[
                'car',
                'truck',
                'construction_vehicle',
                'bus',
                'trailer',
                'barrier',
                'motorcycle',
                'bicycle',
                'pedestrian',
                'traffic_cone',
            ],
            data_root='/workspace/mmdetection3d/data/nuscenes/',
            info_path=
            '/workspace/mmdetection3d/data/nuscenes/nuscenes_dbinfos_train.pkl',
            points_loader=dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            prepare=dict(
                filter_by_difficulty=[
                    -1,
                ],
                filter_by_min_points=dict(
                    barrier=5,
                    bicycle=5,
                    bus=5,
                    car=5,
                    construction_vehicle=5,
                    motorcycle=5,
                    pedestrian=5,
                    traffic_cone=5,
                    trailer=5,
                    truck=5)),
            rate=1.0,
            sample_groups=dict(
                barrier=2,
                bicycle=6,
                bus=4,
                car=2,
                construction_vehicle=7,
                motorcycle=6,
                pedestrian=2,
                traffic_cone=2,
                trailer=6,
                truck=3)),
        type='ObjectSample'),
    dict(
        rot_range=[
            -0.78539816,
            0.78539816,
        ],
        scale_ratio_range=[
            0.9,
            1.1,
        ],
        translation_std=0.5,
        type='BEVFusionGlobalRotScaleTrans'),
    dict(type='BEVFusionRandomFlip3D'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='ObjectRangeFilter'),
    dict(
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='ObjectNameFilter'),
    dict(
        fixed_prob=True,
        max_epoch=6,
        mode=1,
        offset=False,
        prob=0.0,
        ratio=0.5,
        rotate=1,
        type='GridMask',
        use_h=True,
        use_w=True),
    dict(type='PointShuffle'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
            'img_aug_matrix',
            'lidar_aug_matrix',
            'num_pts_feats',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                color_type='color',
                to_float32=True,
                type='BEVLoadMultiViewImageFromFiles'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                load_dim=5,
                pad_empty_sweeps=True,
                remove_close=True,
                sweeps_num=9,
                type='LoadPointsFromMultiSweeps',
                use_dim=5),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.48,
                    0.48,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    54.0,
                    54.0,
                    3.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'img',
                    'points',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='NuScenesDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='/workspace/mmdetection3d/data/nuscenes/nuscenes_infos_val.pkl',
    backend_args=None,
    data_root='/workspace/mmdetection3d/data/nuscenes/',
    metric='bbox',
    type='NuScenesMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
voxel_size = (
    0.15,
    0.15,
    8,
)
window_shape = (
    16,
    16,
    1,
)
work_dir = './work_dirs/cmt_sst_ft'
