backend_args = None
class_names = [
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
]
corruption = 'DUMMY'
corruption_root = '/workspace/mmdetection3d/data/multicorrupt'
custom_hooks = [
    dict(train_module_names=[
        'controller',
    ], type='FreezeLayersHook'),
]
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'projects.BEVFusion.bevfusion',
        'projects.UniM2AE',
        'projects.CMT',
    ])
data_prefix = dict(
    CAM_BACK='samples/CAM_BACK',
    CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
    CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
    CAM_FRONT='samples/CAM_FRONT',
    CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
    CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
    pts='samples/LIDAR_TOP',
    sweeps='sweeps/LIDAR_TOP')
data_root = '/workspace/mmdetection3d/data/nuscenes/'
dataset_type = 'NuScenesCorruptDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
grid_size = (
    720,
    720,
    1,
)
ida_aug_conf = dict(
    H=900,
    W=1600,
    bot_pct_lim=(
        0.0,
        0.0,
    ),
    final_dim=(
        320,
        800,
    ),
    rand_flip=True,
    resize_lim=(
        0.47,
        0.625,
    ),
    rot_lim=(
        0.0,
        0.0,
    ))
img_norm_cfg = dict(
    mean=[
        103.53,
        116.28,
        123.675,
    ],
    std=[
        57.375,
        57.12,
        58.395,
    ],
    to_rgb=False)
input_modality = dict(use_camera=True, use_lidar=True)
launcher = 'none'
load_from = '/workspace/mmdetection3d/work_dirs/ADMN_universal_model/epoch_16.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
metainfo = dict(classes=[
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
])
model = dict(
    controller=dict(layer_budgets=[
        10,
    ], type='UniversalConvLayerController'),
    data_preprocessor=dict(
        type='Det3DDataPreprocessor',
        voxel=True,
        voxel_layer=dict(
            max_num_points=-1,
            max_voxels=(
                -1,
                -1,
            ),
            point_cloud_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            voxel_size=(
                0.15,
                0.15,
                8,
            )),
        voxel_type='dynamic'),
    img_backbone=dict(
        attn_drop_rate=0.0,
        convert_weights=True,
        depths=[
            2,
            2,
            6,
            2,
        ],
        drop_path_rate=0.2,
        drop_rate=0.0,
        embed_dims=96,
        init_cfg=dict(
            checkpoint=
            'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth',
            type='Pretrained'),
        mlp_ratio=4,
        num_heads=[
            3,
            6,
            12,
            24,
        ],
        out_indices=[
            2,
            3,
        ],
        patch_norm=True,
        qk_scale=None,
        qkv_bias=True,
        type='mmdet.SwinTransformer',
        window_size=7,
        with_cp=False),
    img_neck=dict(
        in_channels=[
            384,
            768,
        ], num_outs=2, out_channels=256, type='CPFPN'),
    pts_backbone=dict(
        conv_cfg=dict(bias=False, type='Conv2d'),
        in_channels=128,
        layer_nums=[
            3,
            3,
        ],
        layer_strides=[
            2,
            2,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN2d'),
        out_channels=[
            64,
            128,
        ],
        type='SECOND'),
    pts_bbox_head=dict(
        bbox_coder=dict(
            max_num=300,
            num_classes=10,
            pc_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            post_center_range=[
                -61.2,
                -61.2,
                -10.0,
                61.2,
                61.2,
                10.0,
            ],
            type='MultiTaskBBoxCoder',
            voxel_size=(
                0.15,
                0.15,
                8,
            )),
        common_heads=dict(
            center=(
                2,
                2,
            ),
            dim=(
                3,
                2,
            ),
            height=(
                1,
                2,
            ),
            rot=(
                2,
                2,
            ),
            vel=(
                2,
                2,
            )),
        downsample_scale=4,
        hidden_dim=256,
        in_channels=512,
        loss_bbox=dict(
            loss_weight=0.25, reduction='mean', type='mmdet.L1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2,
            loss_weight=2.0,
            reduction='mean',
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_heatmap=dict(
            loss_weight=1.0, reduction='mean', type='mmdet.GaussianFocalLoss'),
        separate_head=dict(
            final_kernel=1, init_bias=-2.19, type='SeparateTaskHead'),
        tasks=[
            dict(
                class_names=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                num_class=10),
        ],
        transformer=dict(
            decoder=dict(
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='MultiheadAttention'),
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='PETRMultiheadFlashAttention'),
                    ],
                    feedforward_channels=1024,
                    ffn_cfgs=dict(
                        act_cfg=dict(inplace=True, type='ReLU'),
                        embed_dims=256,
                        feedforward_channels=1024,
                        ffn_drop=0.0,
                        num_fcs=2,
                        type='FFN'),
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='PETRTransformerDecoderLayer',
                    with_cp=False),
                type='PETRTransformerDecoder'),
            type='CmtTransformer'),
        type='CmtHead'),
    pts_middle_encoder=dict(
        activation='gelu',
        group_size=256,
        in_channels=128,
        normalize_pos=False,
        num_blocks=2,
        num_heads=8,
        output_shape=[
            720,
            720,
        ],
        pos_temperature=10000,
        sparse_shape=(
            720,
            720,
            1,
        ),
        type='FlatFormer',
        window_shape=(
            16,
            16,
            1,
        )),
    pts_neck=dict(
        in_channels=[
            64,
            128,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN2d'),
        out_channels=[
            256,
            256,
        ],
        type='SECONDFPN',
        upsample_strides=[
            0.5,
            1,
        ]),
    pts_voxel_encoder=dict(
        feat_channels=[
            64,
            128,
        ],
        in_channels=5,
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN1d'),
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        return_gt_points=False,
        type='DynamicVFE_Efficient',
        voxel_size=(
            0.15,
            0.15,
            8,
        ),
        with_cluster_center=True,
        with_distance=False,
        with_voxel_center=True),
    test_cfg=dict(
        pts=dict(
            dataset='nuScenes',
            grid_size=(
                720,
                720,
                1,
            ),
            max_num=200,
            nms_thr=0.2,
            nms_type=None,
            out_size_factor=4,
            pc_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            use_rotate_nms=True,
            voxel_size=(
                0.15,
                0.15,
                8,
            ))),
    train_cfg=dict(
        pts=dict(
            assigner=dict(
                cls_cost=dict(type='mmdet.FocalLossCost', weight=2.0),
                code_weights=[
                    2.0,
                    2.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                    0.2,
                    0.2,
                ],
                iou_cost=dict(type='IoU3DCost_CMT', weight=0.0),
                pc_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                reg_cost=dict(type='BBox3DL1Cost', weight=0.25),
                type='HungarianAssigner3D_CMT'),
            code_weights=[
                2.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.2,
                0.2,
            ],
            dataset='nuScenes',
            gaussian_overlap=0.1,
            grid_size=(
                720,
                720,
                1,
            ),
            min_radius=2,
            out_size_factor=4,
            point_cloud_range=[
                -54.0,
                -54.0,
                -5.0,
                53.95,
                53.95,
                2.95,
            ],
            pos_weight=-1,
            voxel_size=(
                0.15,
                0.15,
                8,
            ))),
    type='CmtDetector',
    use_grid_mask=True)
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=0.001, type='AdamW', weight_decay=0.01),
    type='AmpOptimWrapper')
out_size_factor = 4
param_scheduler = [
    dict(
        begin=0,
        by_epoch=False,
        end=5000,
        end_factor=0.001,
        start_factor=1.0,
        type='LinearLR'),
]
point_cloud_range = [
    -54.0,
    -54.0,
    -5.0,
    53.95,
    53.95,
    2.95,
]
randomness = dict(diff_rank_seed=True, seed=100)
resume = False
severity_distribution = dict({3: 1})
sparse_shape = (
    720,
    720,
    1,
)
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        box_type_3d='LiDAR',
        camera_corruption='beamsreducing',
        corruption_root='/workspace/mmdetection3d/data/multicorrupt',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        lidar_corruption='beamsreducing',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(
                sweeps_num=10,
                type='LoadPointsFromMultiSweeps',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(type='LoadMultiViewImageFromFiles'),
            dict(
                data_aug_conf=dict(
                    H=900,
                    W=1600,
                    bot_pct_lim=(
                        0.0,
                        0.0,
                    ),
                    final_dim=(
                        320,
                        800,
                    ),
                    rand_flip=True,
                    resize_lim=(
                        0.47,
                        0.625,
                    ),
                    rot_lim=(
                        0.0,
                        0.0,
                    )),
                training=False,
                type='ResizeCropFlipImage'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    57.375,
                    57.12,
                    58.395,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='PointsRangeFilter'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'points',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                    'corruption_info',
                ],
                type='Pack3DDetInputs'),
        ],
        return_corruption_info=True,
        severity_distribution=dict({3: 1}),
        test_mode=True,
        type='NuScenesCorruptDataset',
        use_valid_flag=True),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='/workspace/mmdetection3d/data/nuscenes/nuscenes_infos_val.pkl',
    backend_args=None,
    data_root='/workspace/mmdetection3d/data/nuscenes/',
    metric='bbox',
    type='NuScenesMetric')
test_pipeline = [
    dict(
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    dict(
        sweeps_num=10,
        type='LoadPointsFromMultiSweeps',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    dict(type='LoadMultiViewImageFromFiles'),
    dict(
        data_aug_conf=dict(
            H=900,
            W=1600,
            bot_pct_lim=(
                0.0,
                0.0,
            ),
            final_dim=(
                320,
                800,
            ),
            rand_flip=True,
            resize_lim=(
                0.47,
                0.625,
            ),
            rot_lim=(
                0.0,
                0.0,
            )),
        training=False,
        type='ResizeCropFlipImage'),
    dict(
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            57.375,
            57.12,
            58.395,
        ],
        to_rgb=False,
        type='NormalizeMultiviewImage'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='PointsRangeFilter'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        keys=[
            'img',
            'points',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'num_pts_feats',
            'corruption_info',
        ],
        type='Pack3DDetInputs'),
]
train_cfg = dict(by_epoch=False, max_iters=3000, val_interval=4000)
train_dataloader = dict(
    batch_size=3,
    dataset=dict(
        ann_file='nuscenes_infos_train.pkl',
        box_type_3d='LiDAR',
        camera_corruption='DUMMY',
        corruption_root='/workspace/mmdetection3d/data/multicorrupt',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        lidar_corruption='DUMMY',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(
                sweeps_num=10,
                type='LoadPointsFromMultiSweeps',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(type='LoadMultiViewImageFromFiles'),
            dict(
                type='LoadAnnotations3D',
                with_bbox_3d=True,
                with_label_3d=True),
            dict(
                rot_range=[
                    -0.785,
                    0.785,
                ],
                scale_ratio_range=[
                    0.9,
                    1.1,
                ],
                translation_std=[
                    0.5,
                    0.5,
                    0.5,
                ],
                type='GlobalRotScaleTransAll'),
            dict(
                flip_ratio_bev_horizontal=0.5,
                flip_ratio_bev_vertical=0.5,
                sync_2d=False,
                type='CustomRandomFlip3D'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='PointsRangeFilter'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(type='PointShuffle'),
            dict(
                data_aug_conf=dict(
                    H=900,
                    W=1600,
                    bot_pct_lim=(
                        0.0,
                        0.0,
                    ),
                    final_dim=(
                        320,
                        800,
                    ),
                    rand_flip=True,
                    resize_lim=(
                        0.47,
                        0.625,
                    ),
                    rot_lim=(
                        0.0,
                        0.0,
                    )),
                training=True,
                type='ResizeCropFlipImage'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    57.375,
                    57.12,
                    58.395,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'points',
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes',
                    'gt_labels',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'transformation_3d_flow',
                    'pcd_rotation',
                    'pcd_scale_factor',
                    'pcd_trans',
                    'img_aug_matrix',
                    'lidar_aug_matrix',
                    'num_pts_feats',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'corruption_info',
                ],
                type='Pack3DDetInputs'),
        ],
        return_corruption_info=True,
        severity_distribution=dict({3: 1}),
        test_mode=False,
        type='NuScenesCorruptDataset',
        use_valid_flag=True),
    num_workers=12,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    dict(
        sweeps_num=10,
        type='LoadPointsFromMultiSweeps',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    dict(type='LoadMultiViewImageFromFiles'),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(
        rot_range=[
            -0.785,
            0.785,
        ],
        scale_ratio_range=[
            0.9,
            1.1,
        ],
        translation_std=[
            0.5,
            0.5,
            0.5,
        ],
        type='GlobalRotScaleTransAll'),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        sync_2d=False,
        type='CustomRandomFlip3D'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            53.95,
            53.95,
            2.95,
        ],
        type='ObjectRangeFilter'),
    dict(
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='ObjectNameFilter'),
    dict(type='PointShuffle'),
    dict(
        data_aug_conf=dict(
            H=900,
            W=1600,
            bot_pct_lim=(
                0.0,
                0.0,
            ),
            final_dim=(
                320,
                800,
            ),
            rand_flip=True,
            resize_lim=(
                0.47,
                0.625,
            ),
            rot_lim=(
                0.0,
                0.0,
            )),
        training=True,
        type='ResizeCropFlipImage'),
    dict(
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            57.375,
            57.12,
            58.395,
        ],
        to_rgb=False,
        type='NormalizeMultiviewImage'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
            'img_aug_matrix',
            'lidar_aug_matrix',
            'num_pts_feats',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'corruption_info',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        box_type_3d='LiDAR',
        camera_corruption='DUMMY',
        corruption_root='/workspace/mmdetection3d/data/multicorrupt',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='/workspace/mmdetection3d/data/nuscenes/',
        lidar_corruption='DUMMY',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(
                sweeps_num=10,
                type='LoadPointsFromMultiSweeps',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            dict(type='LoadMultiViewImageFromFiles'),
            dict(
                data_aug_conf=dict(
                    H=900,
                    W=1600,
                    bot_pct_lim=(
                        0.0,
                        0.0,
                    ),
                    final_dim=(
                        320,
                        800,
                    ),
                    rand_flip=True,
                    resize_lim=(
                        0.47,
                        0.625,
                    ),
                    rot_lim=(
                        0.0,
                        0.0,
                    )),
                training=False,
                type='ResizeCropFlipImage'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    57.375,
                    57.12,
                    58.395,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    53.95,
                    53.95,
                    2.95,
                ],
                type='PointsRangeFilter'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'points',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                    'corruption_info',
                ],
                type='Pack3DDetInputs'),
        ],
        return_corruption_info=True,
        severity_distribution=dict({3: 1}),
        test_mode=True,
        type='NuScenesCorruptDataset',
        use_valid_flag=True),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='/workspace/mmdetection3d/data/nuscenes/nuscenes_infos_val.pkl',
    backend_args=None,
    data_root='/workspace/mmdetection3d/data/nuscenes/',
    metric='bbox',
    type='NuScenesMetric')
voxel_size = (
    0.15,
    0.15,
    8,
)
window_shape = (
    16,
    16,
    1,
)
work_dir = './work_dirs/ADMN_multicorrupt_universal_test_beamsreducing/ADMN_Controller_10'
